name: obd_vin_decoder
description: "A pure Dart package for offline and online Vehicle Identification Number (VIN) decoding, supporting modern vehicles up to 2039"
version: 0.0.10
homepage: https://github.com/dmuhia136/obd_vin_decoder # Create a GitHub repo for this!

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  http: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
