/// A mapping of Japanese Domestic Market (JDM) chassis prefixes to their Make and Model.
const Map<String, String> jdmPrefixes = {
  "KDH": "Toyota Hiace / Regius",
  "TRH": "Toyota Hiace",
  "NCP": "Toyota Vitz / Ist / Porte",
  "ZVW": "Toyota Prius",
  "ZRT": "Toyota Allion / Premio",
  "NZE": "Toyota Corolla / Fielder",
  "NZT": "Toyota Allion / Premio",
  "ZRE": "Toyota Auris / Corolla",
  "NLP": "Toyota Probox / Succeed",
  "NSP": "Toyota Probox / Vitz",
  "MCU": "Toyota Harrier",
  "ACU": "Toyota Harrier",
  "ZSU": "Toyota Harrier",
  "GGH": "Toyota Alphard / Vellfire",
  "ANH": "Toyota Alphard",
  "URJ": "Toyota Land Cruiser V8",
  "GRJ": "Toyota Land Cruiser Prado",
  "GDJ": "Toyota Prado / Hilux",
  "GUN": "Toyota Hilux (Revo)",
  "VXY": "Nissan Serena",
  "C25": "Nissan Serena",
  "C26": "Nissan Serena",
  "NT31": "Nissan X-Trail",
  "T32": "Nissan X-Trail",
  "VY12": "Nissan AD Van",
  "E11": "Nissan Note",
  "E12": "Nissan Note",
  "K13": "Nissan March",
  "DE3F": "Mazda Demio",
  "DE5F": "Mazda Demio",
  "DJ5F": "Mazda Demio (Skyactiv)",
  "KE2F": "Mazda CX-5",
  "KF2P": "Mazda CX-5",
  "GK3": "Honda Fit",
  "GP5": "Honda Fit Hybrid",
  "RU1": "Honda Vezel",
  "RU3": "Honda Vezel Hybrid",
  "CW5W": "Mitsubishi Outlander",
  "V98": "Mitsubishi Pajero",
  "GP7": "Subaru XV",
  "SJ5": "Subaru Forester",
  "VAG": "Subaru WRX S4",
};