/// A mapping of World Manufacturer Identifier (WMI) codes to manufacturer names.
const Map<String, String> manufacturers = {
  '1G1': 'Chevrolet',
  '1G2': 'Pontiac',
  '1G3': 'Oldsmobile',
  '1G4': 'Buick',
  '1G6': 'Cadillac',
  '1G': 'General Motors',
  '1F': 'Ford Motor Company',
  '1J4': 'Jeep',
  '1J8': 'Jeep',
  '1VW': 'Volkswagen',
  '2T': 'Toyota',
  '2FA': 'Ford Motor Company',
  '2G1': 'Chevrolet',
  '2HG': 'Honda',
  '3VW': 'Volkswagen',
  '3N': 'Nissan',
  '4T': 'Toyota',
  '5N1': 'Nissan',
  '5YJ': 'Tesla, Inc.',
  'JHM': 'Honda',
  'JTD': 'Toyota',
  'JT6': 'Toyota',
  'KL': 'Daewoo General Motors',
  'KM8': 'Hyundai',
  'KND': 'Kia',
  'SAL': 'Land Rover',
  'SAJ': 'Jaguar',
  'TRU': 'Audi',
  'WAU': 'Audi',
  'WBA': 'BMW',
  'WDB': 'Mercedes-Benz',
  'WP0': 'Porsche',
  'WVW': 'Volkswagen',
  'YV1': 'Volvo Cars',
  // Note: Paste the rest of the WMI codes from your snippet here!
};
